services:
  vdb-web:
    image: nginx:1.27-alpine
    container_name: vdb-web
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: vdb-uk.com,www.vdb-uk.com
      VIRTUAL_PORT: "80"
      LETSENCRYPT_HOST: vdb-uk.com,www.vdb-uk.com
      LETSENCRYPT_EMAIL: hannah@vandenberghuk.com
    volumes:
      - /root/arbtechuk/vdb-uk-dot-com/dist:/usr/share/nginx/html:ro
    networks:
      - proxy

networks:
  proxy:
    external: true
